import React from "react";
import FetchTestComp from "./FetchTestComp";
import LoginChecker from "./LoginChecker";
import AdminNavbar from "@/components/navbar/AdminNavbar";
import Footer from "@/components/footer/Footer";
import NavBar from "@/components/navbar/NavBar";

const page = () => {
  return (
    <>
      <LoginChecker>
        <NavBar />
        <FetchTestComp />
        <Footer />
      </LoginChecker>
    </>
  );
};

export default page;

export const metadata = {
  title: "Test Next App",
  description: "Generated by create next app",
};
